version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USERNAME: sb-java-user
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - /init.sql:/docker-entrypoint-initdb.d/init.sql